export const MUNICIPIOS_MS: string[] = [
  'Alcinópolis',
  'Amambai',
  'Anastácio',
  'Anaurilândia',
  'Angélica',
  'Antônio João',
  'Aparecida Do Taboado',
  'Aquidauana',
  'Aral Moreira',
  'Bandeirantes',
  'Bataguassu',
  'Batayporã',
  'Bela Vista',
  'Bodoquena',
  'Bonito',
  'Brasilândia',
  'Caarapó',
  'Camapuã',
  'Campo Grande',
  'Caracol',
  'Cassilândia',
  'Chapadão Do Sul',
  'Corguinho',
  'Coronel Sapucaia',
  'Corumbá',
  'Costa Rica',
  'Coxim',
  'Deodápolis',
  'Dois Irmãos Do Buriti',
  'Douradina',
  'Dourados',
  'Eldorado',
  'Figueirão',
  'Fátima Do Sul',
  'Glória De Dourados',
  'Guia Lopes Da Laguna',
  'Iguatemi',
  'Inocência',
  'Itaporã',
  'Itaquiraí',
  'Ivinhema',
  'Japorã',
  'Jaraguari',
  'Jardim',
  'Jateí',
  'Juti',
  'Ladário',
  'Laguna Carapã',
  'Maracaju',
  'Miranda',
  'Mundo Novo',
  'Naviraí',
  'Nioaque',
  'Nova Alvorada Do Sul',
  'Nova Andradina',
  'Novo Horizonte Do Sul',
  'Paranaíba',
  'Paranhos',
  'Paraíso Das Águas',
  'Pedro Gomes',
  'Ponta Porã',
  'Porto Murtinho',
  'Ribas Do Rio Pardo',
  'Rio Brilhante',
  'Rio Negro',
  'Rio Verde De Mato Grosso',
  'Rochedo',
  'Santa Rita Do Pardo',
  'Selvíria',
  'Sete Quedas',
  'Sidrolândia',
  'Sonora',
  'São Gabriel Do Oeste',
  'Tacuru',
  'Taquarussu',
  'Terenos',
  'Três Lagoas',
  'Vicentina',
  'Água Clara',
];
