ALTER TABLE "ceps_ms"
ADD COLUMN IF NOT EXISTS "ibge_municipio_id" TEXT,
ADD COLUMN IF NOT EXISTS "localidades" JSONB,
ADD COLUMN IF NOT EXISTS "bairro_confianca" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "total_registros" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "localidades_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "logradouros_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "importado_em" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "ceps_ms_origem_idx" ON "ceps_ms"("origem");
